### ISSUE TITLE
RS41 as Arduino board

### ISSUE THREAD

**Issue by iddq** [MakersFunDuck/RS41-Arduino#1]
Hello,

How can we add RS41 board to Arduino IDE?

Thanks

**Comment by MakersFunDuck** [comment]
Hi, I made a video just to show it.
You can find it here:
https://www.youtube.com/watch?v=UC9JDQqAKds

**Comment by iddq** [comment]
I couldn't find what type of board you selected in the Arduino IDE's board manager for programming.

**Comment by MakersFunDuck** [comment]
You can follow this github page.
https://github.com/stm32duino/wiki/wiki/Getting-Started

then you need to select the correct MCU in the Arduino IDE

**Comment by iddq** [comment]
thank you!

Generic F100C8Tx
